var a = 1-(1-1-1-1-1)-1-3
var c = 1 + 101 % 3 / 2
var b = 1-1-1--3*3+1
var d = c + b + a
var e = (2+4*(3/(.2*10))+3-1-1)*1.1+(0.5+.5)+(.5-0.3-0.2)
a = 1
a += a
a -= b
a *= c
a /= d
a = e
a.x
a.x.y
a.x.y.z
a.x.y.z.a

func sqrt(x)
    var result = x * x
    return result
end

var result = sqrt(sqrt(5))
result += 0

func add(a, b)
    var c = a + b
    return c
end

var r = add(add(1,2), add(3,4))
r += 0

func get_nil() 
    return
end

var n = get_nil()
n = 0

func get_n()
    return n
end

var s = get_n()
s += 0

n = get_nil()
n = s
n += 0
